// Date: 2013/8/13 ä¸‹å? 03:24:07
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package EddyExperiment.test02.client;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class ModelSpyro extends ModelBase
{
  //fields
    ModelRenderer RightFrontPaw;
    ModelRenderer WingLeft;
    ModelRenderer LegRightFrontTop;
    ModelRenderer LegRightFrontBottom;
    ModelRenderer LegRightBackTop;
    ModelRenderer LegRightBackBottom;
    ModelRenderer RightBackPaw;
    ModelRenderer LegLeftFrontTop;
    ModelRenderer SnoutRight;
    ModelRenderer LeftFrontPaw;
    ModelRenderer LegLeftBackTop;
    ModelRenderer LegLeftBackBottom;
    ModelRenderer LeftBackPaw;
    ModelRenderer LegLeftFrontBottom;
    ModelRenderer TailPieceSmall;
    ModelRenderer JawPiece;
    ModelRenderer HeadPieceBottom;
    ModelRenderer HeadPieceTop;
    ModelRenderer HornRightBottom;
    ModelRenderer HornLeftBottom;
    ModelRenderer HornRightTop;
    ModelRenderer HornLeftTop;
    ModelRenderer Torso;
    ModelRenderer SnoutLeft;
    ModelRenderer WingPieceLeft;
    ModelRenderer WingRight;
    ModelRenderer WingPieceRight;
    ModelRenderer Neck;
    ModelRenderer TailBack;
    ModelRenderer TailFront;
    ModelRenderer ScaleBackHead;
    ModelRenderer TailPieceLarge;
    ModelRenderer ScaleTailPiece;
    ModelRenderer ScaleHead;
    ModelRenderer ScaleTop1;
    ModelRenderer ScaleBackPiece1;
    ModelRenderer ScaleBackPiece2;
  
  public ModelSpyro()
  {
    textureWidth = 64;
    textureHeight = 64;
    
      RightFrontPaw = new ModelRenderer(this, 12, 31);
      RightFrontPaw.addBox(0F, 5F, -4F, 2, 1, 4);
      RightFrontPaw.setRotationPoint(3F, 18F, -2F);
      RightFrontPaw.setTextureSize(64, 64);
      RightFrontPaw.mirror = true;
      setRotation(RightFrontPaw, 0F, 0F, 0F);
      WingLeft = new ModelRenderer(this, 2, 51);
      WingLeft.addBox(-10F, -1F, -2F, 10, 0, 4);
      WingLeft.setRotationPoint(-1F, 16F, 0F);
      WingLeft.setTextureSize(64, 64);
      WingLeft.mirror = true;
      setRotation(WingLeft, 0.1745329F, 0F, -0.1745329F);
      LegRightFrontTop = new ModelRenderer(this, 20, 19);
      LegRightFrontTop.addBox(0F, 0F, -2F, 2, 3, 3);
      LegRightFrontTop.setRotationPoint(3F, 18F, -2F);
      LegRightFrontTop.setTextureSize(64, 64);
      LegRightFrontTop.mirror = true;
      setRotation(LegRightFrontTop, -0.0872665F, 0F, 0F);
      LegRightFrontBottom = new ModelRenderer(this, 0, 25);
      LegRightFrontBottom.addBox(0F, 2F, -1.5F, 2, 4, 2);
      LegRightFrontBottom.setRotationPoint(3F, 18F, -2F);
      LegRightFrontBottom.setTextureSize(64, 64);
      LegRightFrontBottom.mirror = true;
      setRotation(LegRightFrontBottom, -0.1745329F, 0F, 0F);
      LegRightBackTop = new ModelRenderer(this, 30, 19);
      LegRightBackTop.addBox(0F, 0F, -2F, 2, 3, 3);
      LegRightBackTop.setRotationPoint(3F, 18F, 3F);
      LegRightBackTop.setTextureSize(64, 64);
      LegRightBackTop.mirror = true;
      setRotation(LegRightBackTop, 0.1396263F, 0F, 0F);
      LegRightBackBottom = new ModelRenderer(this, 16, 25);
      LegRightBackBottom.addBox(0F, 2F, -1F, 2, 4, 2);
      LegRightBackBottom.setRotationPoint(3F, 18F, 3F);
      LegRightBackBottom.setTextureSize(64, 64);
      LegRightBackBottom.mirror = true;
      setRotation(LegRightBackBottom, -0.1745329F, 0F, 0F);
      RightBackPaw = new ModelRenderer(this, 36, 31);
      RightBackPaw.addBox(0F, 5F, -3F, 2, 1, 4);
      RightBackPaw.setRotationPoint(3F, 18F, 3F);
      RightBackPaw.setTextureSize(64, 64);
      RightBackPaw.mirror = true;
      setRotation(RightBackPaw, 0F, 0F, 0F);
      LegLeftFrontTop = new ModelRenderer(this, 0, 19);
      LegLeftFrontTop.addBox(-2F, 0F, -1F, 2, 3, 3);
      LegLeftFrontTop.setRotationPoint(-2F, 18F, -3F);
      LegLeftFrontTop.setTextureSize(64, 64);
      LegLeftFrontTop.mirror = true;
      setRotation(LegLeftFrontTop, -0.0872665F, 0F, 0F);
      SnoutRight = new ModelRenderer(this, 48, 2);
      SnoutRight.addBox(1F, -3F, -5F, 1, 1, 1);
      SnoutRight.setRotationPoint(1F, 16F, -3F);
      SnoutRight.setTextureSize(64, 64);
      SnoutRight.mirror = true;
      setRotation(SnoutRight, 0F, 0F, 0F);
      LeftFrontPaw = new ModelRenderer(this, 0, 31);
      LeftFrontPaw.addBox(-2F, 5F, -3F, 2, 1, 4);
      LeftFrontPaw.setRotationPoint(-2F, 18F, -3F);
      LeftFrontPaw.setTextureSize(64, 64);
      LeftFrontPaw.mirror = true;
      setRotation(LeftFrontPaw, 0F, 0F, 0F);
      LegLeftBackTop = new ModelRenderer(this, 10, 19);
      LegLeftBackTop.addBox(-2F, 0F, -2F, 2, 3, 3);
      LegLeftBackTop.setRotationPoint(-2F, 18F, 3F);
      LegLeftBackTop.setTextureSize(64, 64);
      LegLeftBackTop.mirror = true;
      setRotation(LegLeftBackTop, 0.1396263F, 0F, 0F);
      LegLeftBackBottom = new ModelRenderer(this, 24, 25);
      LegLeftBackBottom.addBox(-2F, 2F, -1F, 2, 4, 2);
      LegLeftBackBottom.setRotationPoint(-2F, 18F, 3F);
      LegLeftBackBottom.setTextureSize(64, 64);
      LegLeftBackBottom.mirror = true;
      setRotation(LegLeftBackBottom, -0.1745329F, 0F, 0F);
      LeftBackPaw = new ModelRenderer(this, 24, 31);
      LeftBackPaw.addBox(-2F, 5F, -3F, 2, 1, 4);
      LeftBackPaw.setRotationPoint(-2F, 18F, 3F);
      LeftBackPaw.setTextureSize(64, 64);
      LeftBackPaw.mirror = true;
      setRotation(LeftBackPaw, 0F, 0F, 0F);
      LegLeftFrontBottom = new ModelRenderer(this, 8, 25);
      LegLeftFrontBottom.addBox(-2F, 2F, -0.5F, 2, 4, 2);
      LegLeftFrontBottom.setRotationPoint(-2F, 18F, -3F);
      LegLeftFrontBottom.setTextureSize(64, 64);
      LegLeftFrontBottom.mirror = true;
      setRotation(LegLeftFrontBottom, -0.1745329F, 0F, 0F);
      TailPieceSmall = new ModelRenderer(this, 28, 36);
      TailPieceSmall.addBox(0F, -0.5F, 4F, 1, 1, 1);
      TailPieceSmall.setRotationPoint(0F, 16F, 7F);
      TailPieceSmall.setTextureSize(64, 64);
      TailPieceSmall.mirror = true;
      setRotation(TailPieceSmall, 0.1745329F, 0F, 0F);
      JawPiece = new ModelRenderer(this, 52, 0);
      JawPiece.addBox(-2F, -1F, -4F, 3, 1, 3);
      JawPiece.setRotationPoint(1F, 16F, -3F);
      JawPiece.setTextureSize(64, 64);
      JawPiece.mirror = true;
      setRotation(JawPiece, 0.1745329F, 0F, 0F);
      HeadPieceBottom = new ModelRenderer(this, 30, 7);
      HeadPieceBottom.addBox(-3F, -2F, -5F, 5, 2, 6);
      HeadPieceBottom.setRotationPoint(1F, 16F, -3F);
      HeadPieceBottom.setTextureSize(64, 64);
      HeadPieceBottom.mirror = true;
      setRotation(HeadPieceBottom, 0F, 0F, 0F);
      HeadPieceTop = new ModelRenderer(this, 30, 0);
      HeadPieceTop.addBox(-3F, -5F, -3F, 5, 3, 4);
      HeadPieceTop.setRotationPoint(1F, 16F, -3F);
      HeadPieceTop.setTextureSize(64, 64);
      HeadPieceTop.mirror = true;
      setRotation(HeadPieceTop, 0F, 0F, 0F);
      HornRightBottom = new ModelRenderer(this, 8, 14);
      HornRightBottom.addBox(0F, -6F, -3.5F, 2, 3, 2);
      HornRightBottom.setRotationPoint(1F, 16F, -3F);
      HornRightBottom.setTextureSize(64, 64);
      HornRightBottom.mirror = true;
      setRotation(HornRightBottom, -0.7853982F, 0.7853982F, 0F);
      HornLeftBottom = new ModelRenderer(this, 0, 14);
      HornLeftBottom.addBox(-2.75F, -6.5F, -3F, 2, 3, 2);
      HornLeftBottom.setRotationPoint(1F, 16F, -3F);
      HornLeftBottom.setTextureSize(64, 64);
      HornLeftBottom.mirror = true;
      setRotation(HornLeftBottom, -0.7853982F, -0.7853982F, 0F);
      HornRightTop = new ModelRenderer(this, 20, 14);
      HornRightTop.addBox(0.5F, -9F, -3F, 1, 3, 1);
      HornRightTop.setRotationPoint(1F, 16F, -3F);
      HornRightTop.setTextureSize(64, 64);
      HornRightTop.mirror = true;
      setRotation(HornRightTop, -0.7853982F, 0.7853982F, 0F);
      HornLeftTop = new ModelRenderer(this, 16, 14);
      HornLeftTop.addBox(-2.2F, -9.5F, -2.5F, 1, 3, 1);
      HornLeftTop.setRotationPoint(1F, 16F, -3F);
      HornLeftTop.setTextureSize(64, 64);
      HornLeftTop.mirror = true;
      setRotation(HornLeftTop, -0.7853982F, -0.7853982F, 0F);
      Torso = new ModelRenderer(this, 0, 0);
      Torso.addBox(-2F, -2F, -5F, 5, 4, 10);
      Torso.setRotationPoint(0F, 19F, 0F);
      Torso.setTextureSize(64, 64);
      Torso.mirror = true;
      setRotation(Torso, 0F, 0F, 0F);
      SnoutLeft = new ModelRenderer(this, 48, 0);
      SnoutLeft.addBox(-3F, -3F, -5F, 1, 1, 1);
      SnoutLeft.setRotationPoint(1F, 16F, -3F);
      SnoutLeft.setTextureSize(64, 64);
      SnoutLeft.mirror = true;
      setRotation(SnoutLeft, 0F, 0F, 0F);
      WingPieceLeft = new ModelRenderer(this, 4, 42);
      WingPieceLeft.addBox(-1F, -2F, -1F, 1, 2, 1);
      WingPieceLeft.setRotationPoint(0F, 17.2F, 0F);
      WingPieceLeft.setTextureSize(64, 64);
      WingPieceLeft.mirror = true;
      setRotation(WingPieceLeft, 0.1745329F, 0F, -0.1745329F);
      WingRight = new ModelRenderer(this, 2, 45);
      WingRight.addBox(0F, -1F, -2F, 10, 0, 4);
      WingRight.setRotationPoint(2F, 16F, 0F);
      WingRight.setTextureSize(64, 64);
      WingRight.mirror = true;
      setRotation(WingRight, 0.1745329F, 0F, 0.1745329F);
      WingPieceRight = new ModelRenderer(this, 0, 42);
      WingPieceRight.addBox(-1F, -2F, 0F, 1, 2, 1);
      WingPieceRight.setRotationPoint(2F, 17.5F, -1F);
      WingPieceRight.setTextureSize(64, 64);
      WingPieceRight.mirror = true;
      setRotation(WingPieceRight, 0.1745329F, 0F, 0.1745329F);
      Neck = new ModelRenderer(this, 52, 7);
      Neck.addBox(-1F, -2F, -1F, 3, 3, 3);
      Neck.setRotationPoint(0F, 17F, -4F);
      Neck.setTextureSize(64, 64);
      Neck.mirror = true;
      setRotation(Neck, 0.4537856F, 0F, 0F);
      TailBack = new ModelRenderer(this, 0, 36);
      TailBack.addBox(-1F, -1F, -1F, 2, 2, 4);
      TailBack.setRotationPoint(0.5F, 17.5F, 5F);
      TailBack.setTextureSize(64, 64);
      TailBack.mirror = true;
      setRotation(TailBack, 0.4537856F, 0F, 0F);
      TailFront = new ModelRenderer(this, 12, 36);
      TailFront.addBox(0F, 0F, -1F, 1, 1, 4);
      TailFront.setRotationPoint(0F, 16F, 7F);
      TailFront.setTextureSize(64, 64);
      TailFront.mirror = true;
      setRotation(TailFront, 0.2617994F, 0F, 0F);
      ScaleBackHead = new ModelRenderer(this, 38, 36);
      ScaleBackHead.addBox(-1F, -3F, 2F, 1, 2, 1);
      ScaleBackHead.setRotationPoint(1F, 16F, -4F);
      ScaleBackHead.setTextureSize(64, 64);
      ScaleBackHead.mirror = true;
      setRotation(ScaleBackHead, 0F, 0F, 0F);
      TailPieceLarge = new ModelRenderer(this, 22, 36);
      TailPieceLarge.addBox(0F, -1F, 2F, 1, 2, 2);
      TailPieceLarge.setRotationPoint(0F, 16F, 7F);
      TailPieceLarge.setTextureSize(64, 64);
      TailPieceLarge.mirror = true;
      setRotation(TailPieceLarge, 0.1745329F, 0F, 0F);
      ScaleTailPiece = new ModelRenderer(this, 48, 36);
      ScaleTailPiece.addBox(-0.5F, -2F, 0.2F, 1, 1, 2);
      ScaleTailPiece.setRotationPoint(0.5F, 17.5F, 5F);
      ScaleTailPiece.setTextureSize(64, 64);
      ScaleTailPiece.mirror = true;
      setRotation(ScaleTailPiece, 0.4537856F, 0F, 0F);
      ScaleHead = new ModelRenderer(this, 42, 36);
      ScaleHead.addBox(-1F, -6F, 0F, 1, 2, 2);
      ScaleHead.setRotationPoint(1F, 16F, -3F);
      ScaleHead.setTextureSize(64, 64);
      ScaleHead.mirror = true;
      setRotation(ScaleHead, 0F, 0F, 0F);
      ScaleTop1 = new ModelRenderer(this, 48, 36);
      ScaleTop1.addBox(-1F, -6F, -4F, 1, 1, 2);
      ScaleTop1.setRotationPoint(1F, 16F, -2F);
      ScaleTop1.setTextureSize(64, 64);
      ScaleTop1.mirror = true;
      setRotation(ScaleTop1, 0F, 0F, 0F);
      ScaleBackPiece1 = new ModelRenderer(this, 48, 36);
      ScaleBackPiece1.addBox(0F, -1F, -1F, 1, 1, 2);
      ScaleBackPiece1.setRotationPoint(0F, 17F, 0F);
      ScaleBackPiece1.setTextureSize(64, 64);
      ScaleBackPiece1.mirror = true;
      setRotation(ScaleBackPiece1, 0F, 0F, 0F);
      ScaleBackPiece2 = new ModelRenderer(this, 48, 36);
      ScaleBackPiece2.addBox(0F, -1F, -1F, 1, 1, 2);
      ScaleBackPiece2.setRotationPoint(0F, 17F, 3F);
      ScaleBackPiece2.setTextureSize(64, 64);
      ScaleBackPiece2.mirror = true;
      setRotation(ScaleBackPiece2, 0F, 0F, 0F);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5,entity);
    RightFrontPaw.render(f5);
    WingLeft.render(f5);
    LegRightFrontTop.render(f5);
    LegRightFrontBottom.render(f5);
    LegRightBackTop.render(f5);
    LegRightBackBottom.render(f5);
    RightBackPaw.render(f5);
    LegLeftFrontTop.render(f5);
    SnoutRight.render(f5);
    LeftFrontPaw.render(f5);
    LegLeftBackTop.render(f5);
    LegLeftBackBottom.render(f5);
    LeftBackPaw.render(f5);
    LegLeftFrontBottom.render(f5);
    TailPieceSmall.render(f5);
    JawPiece.render(f5);
    HeadPieceBottom.render(f5);
    HeadPieceTop.render(f5);
    HornRightBottom.render(f5);
    HornLeftBottom.render(f5);
    HornRightTop.render(f5);
    HornLeftTop.render(f5);
    Torso.render(f5);
    SnoutLeft.render(f5);
    WingPieceLeft.render(f5);
    WingRight.render(f5);
    WingPieceRight.render(f5);
    Neck.render(f5);
    TailBack.render(f5);
    TailFront.render(f5);
    ScaleBackHead.render(f5);
    TailPieceLarge.render(f5);
    ScaleTailPiece.render(f5);
    ScaleHead.render(f5);
    ScaleTop1.render(f5);
    ScaleBackPiece1.render(f5);
    ScaleBackPiece2.render(f5);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5,Entity entity)
  {
    super.setRotationAngles(f, f1, f2, f3, f4, f5,entity);
  }

}
